[project]
name = "rightengine"
version = "0.0.1"
description = "C++ Vulkan game engine"
authors = [
    {name = "rbetik12", email = "mr.prikota@gmail.com"}
]
license = {text = "MIT"}
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "conan (==2.9.1)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
package-mode = false

