name: win_x64

on:
  push:
    branches: [ '**' ]
  workflow_dispatch:

jobs:
  build:
    name: Debug build
    runs-on: windows-2022

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup
      uses: ./.github/actions/common-setup-action
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: build
      uses: ./.github/actions/common-build-action
      with:
        conan-profile: win-64-ninja-clang
        build-preset: engine-win-debug
        configuration-preset: debug
  test:
    name: Unit tests (no assert)
    runs-on: windows-2022

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup
      uses: ./.github/actions/common-setup-action
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: build
      uses: ./.github/actions/common-build-action
      with:
        conan-profile: win-64-ninja-clang
        build-preset: engine-win-release-ut
        configuration-preset: release-ut
    
    - name: Test
      shell: powershell
      run: .build\release-ut\.bin\TestLauncher.exe --project Projects\Sandbox\sandbox.project --mode client_no_ui
      
