name: win_x64

on:
  push:
    branches: [ '**' ]
  workflow_dispatch:

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: windows-2022

    steps:
    - uses: actions/checkout@v4
    
    - name: SSH Agent
      uses: webfactory/ssh-agent@v0.5.4
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Pull Git LFS resources
      run: |
        git lfs install 
        git lfs pull

    - name: Check conan cache
      id: cache-conan
      uses: actions/cache@v3
      with:
        path: |
          ~/.conan2
          ~/.conan
        key: ${{ runner.os }}-conan-cache

    - name: Prepare Vulkan SDK
      uses: humbletim/setup-vulkan-sdk@main
      with:
        vulkan-query-version: 1.3.268.0
        vulkan-components: Vulkan-Headers, Vulkan-Loader
        vulkan-use-cache: true

    - name: Prepare conan environment
      run: python Scripts/prepare_env.py

    - name: Prepare conan packages and Visual Studio solution
      run: python Scripts/generate_solution.py win-release win-64

    - name: Build
      run: cmake --build .build/Win --config ${{env.BUILD_TYPE}} --parallel 4
  test:
    name: Unit tests (no assert)
    runs-on: windows-2022

    steps:
    - uses: actions/checkout@v4
    
    - name: SSH Agent
      uses: webfactory/ssh-agent@v0.5.4
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Pull Git LFS resources
      run: |
        git lfs install 
        git lfs pull

    - name: Check conan cache
      id: cache-conan
      uses: actions/cache@v3
      with:
        path: |
          ~/.conan2
          ~/.conan
        key: ${{ runner.os }}-conan-cache

    - name: Prepare Vulkan SDK
      uses: humbletim/setup-vulkan-sdk@main
      with:
        vulkan-query-version: 1.3.268.0
        vulkan-components: Vulkan-Headers, Vulkan-Loader
        vulkan-use-cache: true

    - name: Prepare conan environment
      run: python Scripts/prepare_env.py

    - name: Prepare conan packages and Visual Studio solution
      run: python Scripts/generate_solution.py win-release-ut win-64

    - name: Build
      run: cmake --build .build/Win --config ${{env.BUILD_TYPE}} --parallel 4
    
    - name: Test
      run: .build/Win/.bin/Release/TestLauncher.exe --project Projects/Sandbox/sandbox.project --mode client_no_ui
      
