name: win_x64

on:
  push:
    branches: [ '**' ]
  workflow_dispatch:

env:
  CLANG_VERSION: "17.0.3"
  VULKAN_VERSION: 1.3.268.0
  NINJA_VERSION: 1.12.1

jobs:
  build:
    name: Debug build
    runs-on: windows-2022

    steps:
    - uses: actions/checkout@v4

    - name: Setup
      uses: ./.github/actions/common-setup-action
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
        llvm-version: ${{env.CLANG_VERSION}}
        vulkan-version: ${{env.VULKAN_VERSION}}
        ninja-version: ${{env.NINJA_VERSION}}

    - name: Prepare conan environment
      run: python Scripts/prepare_env.py win-64-ninja-clang

    - name: Generate solution
      run: cmake --preset debug

    - name: Build
      run: cmake --build --preset engine-win-debug --parallel 4
  test:
    name: Unit tests (no assert)
    runs-on: windows-2022

    steps:
    - uses: actions/checkout@v4

    - name: Setup
      uses: ./.github/actions/common-setup-action
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
        llvm-version: ${{env.CLANG_VERSION}}
        vulkan-version: ${{env.VULKAN_VERSION}}
        ninja-version: ${{env.NINJA_VERSION}}

    - name: Prepare conan environment
      run: python Scripts/prepare_env.py win-64-ninja-clang

    - name: Generate solution
      run: cmake --preset release-ut

    - name: Build
      run: cmake --build --preset engine-win-release-ut --parallel 4
    
    - name: Test
      run: .build/release-ut/.bin/TestLauncher.exe --project Projects/Sandbox/sandbox.project --mode client_no_ui
      
